M48
; DRILL file KiCad 10.0.3+dfsg-1 date 2026-09-06T21:22:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-06T21:22:59-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T7C3.500
%
G90
G05
T1
X83.47Y-80.37
X83.47Y-86.15
T2
X125.59Y-56.714
X125.59Y-58.746
X130.67Y-57.73
T3
X94.701Y-145.782
T4
X82.33Y-66.62
T5
X86.83Y-66.62
T6
X84.764Y-94.984
X126.13Y-136.35
T7
X84.71Y-136.36
X126.06Y-94.91
M30
